brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
namesrvAddr = rocketmq-nameserver-dev:9876
# 开发环境：后端跑在宿主机 IDE 里，NameServer 返回的 Broker 地址必须是宿主可达的 127.0.0.1
brokerIP1 = 127.0.0.1
autoCreateTopicEnable = true
